name: Collab
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  google_nav_bar: ^5.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_database: ^10.5.5
  cloud_firestore_web: ^3.12.3
  cloud_firestore: ^4.17.3
  image_picker: ^1.1.2
  firebase_storage: ^11.7.5
  firebase_storage_web: ^3.9.6
  file_picker: ^8.0.3
  image_picker_for_web: ^3.0.4
  popover: ^0.3.0+1
  intl: ^0.18.0
  dropdown_button2: ^2.3.8
  firebase_app_check: ^0.2.2+7
  flutter_stripe: ^10.2.0
  http: ^1.2.1
  flutter_stripe_web: ^5.2.0
  flutter_timer_countdown: ^1.0.7
  carousel_slider: ^4.2.1
  liquid_pull_to_refresh: ^3.0.1
  flutter_spinkit: ^5.2.1
  rename: ^3.0.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/collab_logo.png"
 
  web:
    generate: true
    image_path: "assets/logo/collab_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#0000FF"

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

 
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/onboard/
    - assets/images/home/
    - assets/images/hat.png
    - assets/images/profile.png
