// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf1H5evCkMLXU6CBLwXA2sLjLiFrt5jMI',
    appId: '1:1009362295284:web:0905776db311e396e501a1',
    messagingSenderId: '1009362295284',
    projectId: 'collab-3e621',
    authDomain: 'collab-3e621.firebaseapp.com',
    storageBucket: 'collab-3e621.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmfeiC3-tXKzzp1VrrjLrLOAP3M0S3-Ak',
    appId: '1:1009362295284:android:0b43f12c5ae8ceabe501a1',
    messagingSenderId: '1009362295284',
    projectId: 'collab-3e621',
    storageBucket: 'collab-3e621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAzov6r8rnWatuN15SFbHCOW04sXW1tD0',
    appId: '1:1009362295284:ios:36256ab960272c61e501a1',
    messagingSenderId: '1009362295284',
    projectId: 'collab-3e621',
    storageBucket: 'collab-3e621.appspot.com',
    iosBundleId: 'com.example.collab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAzov6r8rnWatuN15SFbHCOW04sXW1tD0',
    appId: '1:1009362295284:ios:36256ab960272c61e501a1',
    messagingSenderId: '1009362295284',
    projectId: 'collab-3e621',
    storageBucket: 'collab-3e621.appspot.com',
    iosBundleId: 'com.example.collab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf1H5evCkMLXU6CBLwXA2sLjLiFrt5jMI',
    appId: '1:1009362295284:web:f38c968eb2bb6a28e501a1',
    messagingSenderId: '1009362295284',
    projectId: 'collab-3e621',
    authDomain: 'collab-3e621.firebaseapp.com',
    storageBucket: 'collab-3e621.appspot.com',
  );
}
